apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-08-14T15:15:34Z"
  generation: 1
  labels:
    app: flask-app
  name: flask-app
  namespace: exam-adxamov
  resourceVersion: "7020646"
  uid: cc231957-a8e5-4091-8057-49be565bbdac
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: flask-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-app
    spec:
      containers:
      - image: nvrbckdown/flask-app:v1
        imagePullPolicy: IfNotPresent
        name: flask-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
