apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: one-deploy
spec:
  rules:
  - host: aadkhamov.nvrbckdown.uz
    http:
      paths:
      - backend:
          service:
            name: flask-app
            port:
              number: 80
        path: /
        pathType: Exact
status:
  loadBalancer: {}
